"""remove thread unique constraint

Revision ID: 997285ba0334
Revises: 6f687be2ebfa
Create Date: 2022-04-05 17:37:43.196836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997285ba0334'
down_revision = '6f687be2ebfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_thread', table_name='post')
    op.create_index(op.f('ix_post_thread'), 'post', ['thread'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_thread'), table_name='post')
    op.create_index('ix_post_thread', 'post', ['thread'], unique=False)
    # ### end Alembic commands ###
