"""adjusted tags for better handling

Revision ID: d28bac936701
Revises: f9483780ba5d
Create Date: 2022-06-11 11:55:32.385343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28bac936701'
down_revision = 'f9483780ba5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_response', sa.Column('response_to_post_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'post_response', type_='foreignkey')
    op.create_foreign_key(None, 'post_response', 'post', ['response_to_post_id'], ['id'])
    op.drop_column('post_response', 'response_to_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_response', sa.Column('response_to_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'post_response', type_='foreignkey')
    op.create_foreign_key(None, 'post_response', 'post', ['response_to_id'], ['id'])
    op.drop_column('post_response', 'response_to_post_id')
    # ### end Alembic commands ###
